# Generated by Django 3.2.5 on 2021-07-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_tagclass_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageclass',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
